default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") %>
  username: <%= ENV.fetch("DB_USER") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>


test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST") %>
  username: <%= ENV.fetch("DB_USER") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>


production:
  <<: *default
  database: banking_api_production
  username: banking_api
  password: <%= ENV["BANKING_API_DATABASE_PASSWORD"] %>
